name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecutar todos los días a las 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: Laanga
          svg_out_path: dist/github-snake.svg
          gif_out_path: dist/github-snake.gif

      - name: Commit & Push to repo
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add dist/
          git commit -m "🐍 actualiza snake"
          git push
